title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     introduction-to-javascript-course
  repo:     introduction-to-javascript

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: Set up working environment 
- title: Setting up your environment
  description: Learn how to set up an environment to run JavaScript in easily.
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: Learn data types
- title: JavaScript data types
  description: Learn the most common JavaScript data types, and some of the others.
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: Performing methods and functions
- title: Using methods and functions
  description: Learn how methods and functions work, how to use them, and how to create them.
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: Using classes and constructors
- title: Using classes and constructors
  description: Learn what a class is, how it goes together with constructors, and how you should use it.
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: Going hand-to-hand with the HTML DOM
- title: Going hand-to-hand with the HTML DOM
  description: Learn how JavaScript can go greatly with the HTML DOM, and how it can interpret its data.
  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

